[package]
name = "rust-examples"
version = "0.1.0"
authors = ["Sushil Chhetri <chhetrisushil@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
